import { CertificationRequirement } from '@/types/content';

export const COURSE_CERTIFICATION_POLICIES: Record<string, CertificationRequirement> = {
  python: {
    pathSlug: 'python',
    certificationStatus: 'ready',
    certificateEnabled: true,
    requireLessonsCompleted: true,
    minLessonCompletionPercent: 90,
    requireProjectsCompleted: true,
    minMasteryPercentage: 80,
    requireFinalAssessmentPassed: true,
    minFinalAssessmentScorePercent: 80,
    requiredAssessmentSlugs: ['python-mastery-final-exam'],
    certificateType: 'mastery',
    skillsCovered: [
      'Python 3 Syntax & Fundamentals',
      'Data Structures & Algorithms',
      'Object-Oriented Programming (OOP)',
      'Asynchronous Concurrency (asyncio)',
      'FastAPI & REST Architecture',
      'SQL Databases & ORM',
      'Performance Profiling & Memory Optimization',
      'System Architecture & Security',
    ],
  },
  java: {
    pathSlug: 'java',
    certificationStatus: 'ready',
    certificateEnabled: true,
    requireLessonsCompleted: true,
    minLessonCompletionPercent: 100,
    requireProjectsCompleted: true,
    minMasteryPercentage: 80,
    requireFinalAssessmentPassed: true,
    minFinalAssessmentScorePercent: 80,
    requiredAssessmentSlugs: ['java-enterprise-assessment'],
    certificateType: 'completion',
    skillsCovered: ['Java 21 Syntax', 'OOP Concepts', 'Java Collections', 'Multithreading', 'JVM Internals'],
  },
  javascript: {
    pathSlug: 'javascript',
    certificationStatus: 'ready',
    certificateEnabled: true,
    requireLessonsCompleted: true,
    minLessonCompletionPercent: 100,
    requireProjectsCompleted: true,
    minMasteryPercentage: 80,
    requireFinalAssessmentPassed: true,
    minFinalAssessmentScorePercent: 80,
    requiredAssessmentSlugs: ['javascript-es6-async-assessment'],
    certificateType: 'completion',
    skillsCovered: ['ES6+ Syntax', 'Closures', 'Promises & Async/Await', 'Event Loop', 'DOM Manipulation'],
  },
  dsa: {
    pathSlug: 'dsa',
    certificationStatus: 'ready',
    certificateEnabled: true,
    requireLessonsCompleted: true,
    minLessonCompletionPercent: 100,
    requireProjectsCompleted: true,
    minMasteryPercentage: 80,
    requireFinalAssessmentPassed: true,
    minFinalAssessmentScorePercent: 80,
    requiredAssessmentSlugs: ['dsa-asymptotic-complexity-assessment'],
    certificateType: 'mastery',
    skillsCovered: ['Big-O Asymptotic Analysis', 'Binary Trees & BST', 'Graph BFS/DFS', 'Dynamic Programming', 'Sorting Algorithms'],
  },
  'web-security': {
    pathSlug: 'web-security',
    certificationStatus: 'ready',
    certificateEnabled: true,
    requireLessonsCompleted: true,
    minLessonCompletionPercent: 100,
    requireProjectsCompleted: true,
    minMasteryPercentage: 80,
    requireFinalAssessmentPassed: true,
    minFinalAssessmentScorePercent: 80,
    requiredAssessmentSlugs: ['web-security-owasp-assessment'],
    certificateType: 'completion',
    skillsCovered: ['OWASP Top 10', 'XSS Prevention', 'SQLi Defense', 'Security Headers', 'Auth Vulnerabilities'],
  },
  dbms: {
    pathSlug: 'dbms',
    certificationStatus: 'ready',
    certificateEnabled: true,
    requireLessonsCompleted: true,
    minLessonCompletionPercent: 100,
    requireProjectsCompleted: true,
    minMasteryPercentage: 80,
    requireFinalAssessmentPassed: true,
    minFinalAssessmentScorePercent: 80,
    requiredAssessmentSlugs: ['sql-relational-dbms-assessment'],
    certificateType: 'completion',
    skillsCovered: ['SQL Queries', 'PostgreSQL', 'Database Normalization', 'B-Tree Indexes', 'Transactions'],
  },
  'system-design': {
    pathSlug: 'system-design',
    certificationStatus: 'ready',
    certificateEnabled: true,
    requireLessonsCompleted: true,
    minLessonCompletionPercent: 100,
    requireProjectsCompleted: true,
    minMasteryPercentage: 80,
    requireFinalAssessmentPassed: true,
    minFinalAssessmentScorePercent: 80,
    requiredAssessmentSlugs: ['system-design-cap-assessment'],
    certificateType: 'mastery',
    skillsCovered: ['CAP Theorem', 'Load Balancing', 'Database Sharding', 'Microservices', 'Distributed Caching'],
  },
  'interview-preparation': {
    pathSlug: 'interview-preparation',
    certificationStatus: 'ready',
    certificateEnabled: true,
    requireLessonsCompleted: true,
    minLessonCompletionPercent: 100,
    requireProjectsCompleted: true,
    minMasteryPercentage: 80,
    requireFinalAssessmentPassed: true,
    minFinalAssessmentScorePercent: 80,
    requiredAssessmentSlugs: ['interview-prep-coding-behavioral-assessment'],
    certificateType: 'completion',
    skillsCovered: ['Algorithmic Patterns', 'System Design Framework', 'STAR Behavioral Method', 'Mock Coding Interviews'],
  },

  // Courses with certification in development
  react: {
    pathSlug: 'react',
    certificationStatus: 'development',
    certificateEnabled: false,
    minLessonCompletionPercent: 100,
    requiredAssessmentSlugs: ['react-nextjs-architecture-assessment'],
    certificateType: 'completion',
    skillsCovered: ['React 19', 'JSX', 'Hooks (useState, useEffect)', 'Context API', 'Next.js App Router'],
    developmentReason: 'React 19 Server Components and final certification examination are currently in active development.',
  },
  'html-css': {
    pathSlug: 'html-css',
    certificationStatus: 'development',
    certificateEnabled: false,
    minLessonCompletionPercent: 100,
    requiredAssessmentSlugs: ['html-css-modern-web-assessment'],
    certificateType: 'completion',
    skillsCovered: ['HTML5 Semantics', 'CSS Flexbox', 'CSS Grid', 'Responsive Design', 'Accessibility'],
    developmentReason: 'Web Accessibility (a11y) practical labs and final examination are currently in development.',
  },
  'genai-llm-agents': {
    pathSlug: 'genai-llm-agents',
    certificationStatus: 'development',
    certificateEnabled: false,
    minLessonCompletionPercent: 100,
    requiredAssessmentSlugs: ['genai-llm-agents-architecture-assessment'],
    certificateType: 'mastery',
    skillsCovered: ['LLMs & Transformers', 'Embeddings', 'Vector Databases', 'RAG Architecture', 'AI Agents'],
    developmentReason: 'Autonomous Agent evaluation labs and final certification exam are currently in development.',
  },
  'linux-security': {
    pathSlug: 'linux-security',
    certificationStatus: 'development',
    certificateEnabled: false,
    minLessonCompletionPercent: 100,
    requiredAssessmentSlugs: ['linux-security-administration-assessment'],
    certificateType: 'completion',
    skillsCovered: ['Linux CLI Commands', 'File Permissions (chmod)', 'Process Management', 'Bash Scripting', 'System Monitoring'],
    developmentReason: 'Linux Kernel & Shell Automation assessment module is currently in development.',
  },
  'git-github': {
    pathSlug: 'git-github',
    certificationStatus: 'development',
    certificateEnabled: false,
    minLessonCompletionPercent: 100,
    requiredAssessmentSlugs: ['git-github-workflow-assessment'],
    certificateType: 'completion',
    skillsCovered: ['Git CLI', 'Branching & Merging', 'Pull Requests', 'Git Rebase', 'GitHub Actions'],
    developmentReason: 'Advanced Git Rebase simulation labs are currently in development.',
  },
  'cloud-devops': {
    pathSlug: 'cloud-devops',
    certificationStatus: 'development',
    certificateEnabled: false,
    minLessonCompletionPercent: 100,
    requiredAssessmentSlugs: ['cloud-devops-infrastructure-assessment'],
    certificateType: 'mastery',
    skillsCovered: ['AWS Cloud Services', 'Docker Containers', 'Kubernetes', 'Terraform IaC', 'GitHub Actions CI/CD'],
    developmentReason: 'Kubernetes cluster deployment assessment environment is currently in development.',
  },
  'software-testing': {
    pathSlug: 'software-testing',
    certificationStatus: 'development',
    certificateEnabled: false,
    minLessonCompletionPercent: 100,
    requiredAssessmentSlugs: ['software-testing-qa-assessment'],
    certificateType: 'completion',
    skillsCovered: ['Unit Testing', 'Integration Testing', 'TDD Workflow', 'Mocking & Spies', 'Code Coverage'],
    developmentReason: 'Automated E2E Test Suite assessment module is currently in development.',
  },
};

export function getCertificationPolicy(pathSlug: string): CertificationRequirement {
  const policy = COURSE_CERTIFICATION_POLICIES[pathSlug];
  if (!policy) {
    throw new Error(`[Certification Policy Error] Active course '${pathSlug}' has no registered certification policy.`);
  }
  return policy;
}
